-- Staff Attendance Application
-- PostgreSQL / Supabase schema
-- Run this script in the Supabase SQL Editor.
-- The Kivy app should use the school id from the schools table as ASOLO_SCHOOL_ID.

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Schools and application configuration
-- -----------------------------------------------------------------------------
create table if not exists public.schools (
    id text primary key,
    name text not null,
    logo_url text,
    timezone text not null default 'Africa/Kampala',
    enabled boolean not null default true,
    status_message text,
    created_at timestamptz not null default now()
);

create table if not exists public.school_memberships (
    school_id text not null references public.schools(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null default 'staff'
        check (role in ('staff', 'admin', 'builder')),
    created_at timestamptz not null default now(),
    primary key (school_id, user_id)
);

create table if not exists public.user_profiles (
    user_id uuid not null references auth.users(id) on delete cascade,
    school_id text not null references public.schools(id) on delete cascade,
    username text not null,
    email text not null,
    role text not null default 'staff'
        check (role in ('staff', 'admin', 'builder')),
    created_at timestamptz not null default now(),
    primary key (user_id, school_id),
    unique (school_id, username),
    unique (school_id, email)
);

create table if not exists public.school_settings (
    school_id text primary key references public.schools(id) on delete cascade,
    term_days integer not null default 0 check (term_days >= 0),
    updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Staff and attendance
-- -----------------------------------------------------------------------------
create table if not exists public.staff (
    id text not null,
    school_id text not null references public.schools(id) on delete cascade,
    name text not null,
    staff_number text not null,
    department text not null,
    email text not null,
    created_at timestamptz not null default now(),
    primary key (school_id, id),
    unique (school_id, staff_number),
    unique (school_id, email)
);

create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    school_id text not null references public.schools(id) on delete cascade,
    staff_id text not null,
    attendance_date date not null default current_date,
    time_in timestamptz,
    time_out timestamptz,
    is_late boolean not null default false,
    created_at timestamptz not null default now(),
    constraint attendance_staff_fk
        foreign key (school_id, staff_id)
        references public.staff(school_id, id)
        on delete cascade,
    unique (school_id, staff_id, attendance_date),
    check (time_out is null or time_in is not null),
    check (time_out is null or time_out >= time_in)
);

-- -----------------------------------------------------------------------------
-- Audit activity and application status
-- -----------------------------------------------------------------------------
create table if not exists public.activity_logs (
    id bigint generated by default as identity primary key,
    school_id text not null references public.schools(id) on delete cascade,
    user_id uuid references auth.users(id) on delete set null,
    username text,
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.application_status (
    school_id text primary key references public.schools(id) on delete cascade,
    enabled boolean not null default true,
    message text,
    updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------
create index if not exists staff_school_name_idx
    on public.staff (school_id, name);
create index if not exists attendance_school_date_idx
    on public.attendance (school_id, attendance_date);
create index if not exists attendance_school_staff_date_idx
    on public.attendance (school_id, staff_id, attendance_date);
create index if not exists activity_school_created_idx
    on public.activity_logs (school_id, created_at desc);

-- -----------------------------------------------------------------------------
-- Helper functions used by the attendance workflow
-- -----------------------------------------------------------------------------
create or replace function public.record_staff_entry(
    p_school_id text,
    p_staff_id text,
    p_time_in timestamptz default now(),
    p_late boolean default false
)
returns public.attendance
language plpgsql
security definer
set search_path = public
as $$
declare
    saved public.attendance;
    school_timezone text;
    recorded_time timestamptz := now();
begin
    if not exists (
        select 1 from public.school_memberships
        where school_id = p_school_id
          and user_id = auth.uid()
          and role in ('admin', 'builder')
    ) then
        raise exception 'Administrator permission is required';
    end if;
    select timezone into school_timezone
    from public.schools
    where id = p_school_id and enabled;
    if school_timezone is null then
        raise exception 'School is not active or does not exist';
    end if;

    insert into public.attendance (
        school_id, staff_id, attendance_date, time_in, is_late
    ) values (
        p_school_id,
        p_staff_id,
        (recorded_time at time zone school_timezone)::date,
        recorded_time,
        (recorded_time at time zone school_timezone)::time > time '07:30'
    )
    returning * into saved;

    return saved;
exception
    when unique_violation then
        raise exception 'Attendance has already been recorded today';
end;
$$;

create or replace function public.record_staff_exit(
    p_school_id text,
    p_staff_id text,
    p_time_out timestamptz default now()
)
returns public.attendance
language plpgsql
security definer
set search_path = public
as $$
declare
    saved public.attendance;
    school_timezone text;
    recorded_time timestamptz := now();
begin
    if not exists (
        select 1 from public.school_memberships
        where school_id = p_school_id
          and user_id = auth.uid()
          and role in ('admin', 'builder')
    ) then
        raise exception 'Administrator permission is required';
    end if;
    select timezone into school_timezone
    from public.schools
    where id = p_school_id and enabled;
    if school_timezone is null then
        raise exception 'School is not active or does not exist';
    end if;

    update public.attendance
    set time_out = recorded_time
    where school_id = p_school_id
      and staff_id = p_staff_id
      and attendance_date = (recorded_time at time zone school_timezone)::date
      and time_in is not null
      and time_out is null
    returning * into saved;

    if not found then
        raise exception 'Staff entry must be recorded before exit';
    end if;

    return saved;
end;
$$;

revoke execute on function public.record_staff_entry(text, text, timestamptz, boolean)
    from public, anon;
grant execute on function public.record_staff_entry(text, text, timestamptz, boolean)
    to authenticated;
revoke execute on function public.record_staff_exit(text, text, timestamptz)
    from public, anon;
grant execute on function public.record_staff_exit(text, text, timestamptz)
    to authenticated;

-- -----------------------------------------------------------------------------
-- Row-level security
-- -----------------------------------------------------------------------------
alter table public.schools enable row level security;
alter table public.school_memberships enable row level security;
alter table public.user_profiles enable row level security;
alter table public.school_settings enable row level security;
alter table public.staff enable row level security;
alter table public.attendance enable row level security;
alter table public.activity_logs enable row level security;
alter table public.application_status enable row level security;

create or replace function public.is_school_member(target_school_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.school_memberships
        where school_id = target_school_id
          and user_id = auth.uid()
    );
$$;

create or replace function public.is_school_admin(target_school_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.school_memberships
        where school_id = target_school_id
          and user_id = auth.uid()
          and role in ('admin', 'builder')
    );
$$;

create policy schools_member_read on public.schools
    for select to authenticated
    using (public.is_school_member(id));

create policy memberships_self_read on public.school_memberships
    for select to authenticated
    using (user_id = auth.uid() or public.is_school_admin(school_id));

create policy profiles_self_read on public.user_profiles
    for select to authenticated
    using (user_id = auth.uid() or public.is_school_admin(school_id));
create policy profiles_admin_write on public.user_profiles
    for all to authenticated
    using (public.is_school_admin(school_id))
    with check (public.is_school_admin(school_id));

create policy settings_member_read on public.school_settings
    for select to authenticated
    using (public.is_school_member(school_id));
create policy settings_admin_write on public.school_settings
    for all to authenticated
    using (public.is_school_admin(school_id))
    with check (public.is_school_admin(school_id));

create policy staff_member_read on public.staff
    for select to authenticated
    using (public.is_school_member(school_id));
create policy staff_admin_write on public.staff
    for all to authenticated
    using (public.is_school_admin(school_id))
    with check (public.is_school_admin(school_id));

create policy attendance_member_read on public.attendance
    for select to authenticated
    using (public.is_school_member(school_id));
drop policy if exists attendance_member_write on public.attendance;
drop policy if exists attendance_admin_update on public.attendance;
drop policy if exists attendance_member_exit_update on public.attendance;

create policy activity_member_read on public.activity_logs
    for select to authenticated
    using (public.is_school_member(school_id));
create policy activity_member_insert on public.activity_logs
    for insert to authenticated
    with check (public.is_school_member(school_id));

create policy status_member_read on public.application_status
    for select to authenticated
    using (public.is_school_member(school_id));
create policy status_admin_write on public.application_status
    for all to authenticated
    using (public.is_school_admin(school_id))
    with check (public.is_school_admin(school_id));

-- -----------------------------------------------------------------------------
-- Example initial setup. Replace values before running.
-- -----------------------------------------------------------------------------
-- insert into public.schools (id, name, timezone)
-- values ('school-001', 'Your School Name', 'Africa/Kampala');
-- insert into public.school_settings (school_id) values ('school-001');
-- insert into public.application_status (school_id) values ('school-001');
-- After creating a user in Supabase Auth, add that user's UUID here:
-- insert into public.school_memberships (school_id, user_id, role)
-- values ('school-001', '00000000-0000-0000-0000-000000000000', 'admin');
-- insert into public.user_profiles (user_id, school_id, username, email, role)
-- values ('00000000-0000-0000-0000-000000000000', 'school-001',
--         'admin@example.com', 'admin@example.com', 'admin');
