-- Owner controls for the multi-school deployment.
-- Run database_schema.sql first, then run this migration.
-- This migration never stores, returns, or emails passwords.

create table if not exists public.platform_owners (
    user_id uuid primary key references auth.users(id) on delete cascade,
    email text not null unique,
    created_at timestamptz not null default now()
);

alter table public.platform_owners enable row level security;

create or replace function public.is_platform_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.platform_owners
        where user_id = auth.uid()
    );
$$;

create table if not exists public.owner_events (
    id bigint generated by default as identity primary key,
    school_id text not null references public.schools(id) on delete cascade,
    event_type text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.owner_events enable row level security;

create or replace function public.owner_list_schools()
returns table (
    id text,
    name text,
    enabled boolean,
    status_message text,
    created_at timestamptz,
    member_count bigint,
    last_activity timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    if not public.is_platform_owner() then
        raise exception 'Platform owner permission required';
    end if;

    return query
    select
        s.id,
        s.name,
        coalesce(a.enabled, s.enabled) as enabled,
        coalesce(a.message, s.status_message, '') as status_message,
        s.created_at,
        (select count(*) from public.school_memberships m where m.school_id = s.id),
        (select max(l.created_at) from public.activity_logs l where l.school_id = s.id)
    from public.schools s
    left join public.application_status a on a.school_id = s.id
    order by s.name;
end;
$$;

create or replace function public.owner_set_school_access(
    p_school_id text,
    p_enabled boolean,
    p_message text default null
)
returns public.application_status
language plpgsql
security definer
set search_path = public
as $$
declare
    saved public.application_status;
begin
    if not public.is_platform_owner() then
        raise exception 'Platform owner permission required';
    end if;

    if not exists (select 1 from public.schools where id = p_school_id) then
        raise exception 'School does not exist';
    end if;

    update public.schools
    set enabled = p_enabled,
        status_message = nullif(trim(coalesce(p_message, '')), '')
    where id = p_school_id;

    insert into public.application_status (school_id, enabled, message, updated_at)
    values (
        p_school_id,
        p_enabled,
        nullif(trim(coalesce(p_message, '')), ''),
        now()
    )
    on conflict (school_id) do update
    set enabled = excluded.enabled,
        message = excluded.message,
        updated_at = excluded.updated_at
    returning * into saved;

    return saved;
end;
$$;

create or replace function public.record_owner_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_op = 'INSERT' then
        insert into public.owner_events (school_id, event_type, details)
        values (
            new.school_id,
            'school_access_changed',
            jsonb_build_object(
                'enabled', new.enabled,
                'message', coalesce(new.message, '')
            )
        );
    elsif old.enabled is distinct from new.enabled
          or old.message is distinct from new.message then
        insert into public.owner_events (school_id, event_type, details)
        values (
            new.school_id,
            'school_access_changed',
            jsonb_build_object(
                'enabled', new.enabled,
                'message', coalesce(new.message, '')
            )
        );
    end if;
    return new;
end;
$$;

drop trigger if exists application_status_owner_event on public.application_status;
create trigger application_status_owner_event
after insert or update on public.application_status
for each row execute function public.record_owner_event();

create or replace function public.record_school_activity_owner_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (
        select 1
        from public.owner_events
        where school_id = new.school_id
          and event_type = 'school_activity'
          and created_at >= current_date
    ) then
        insert into public.owner_events (school_id, event_type, details)
        values (
            new.school_id,
            'school_activity',
            jsonb_build_object('action', new.action)
        );
    end if;
    return new;
end;
$$;

drop trigger if exists activity_logs_owner_event on public.activity_logs;
create trigger activity_logs_owner_event
after insert on public.activity_logs
for each row execute function public.record_school_activity_owner_event();

revoke all on public.platform_owners from anon, authenticated;
revoke all on public.owner_events from anon, authenticated;
grant execute on function public.owner_list_schools() to authenticated;
grant execute on function public.owner_set_school_access(text, boolean, text) to authenticated;
